version: '3'
services:
  db:
    build: containers/postgres
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"

  repl:
    build: .
    command: lein repl
    ports:
      - "3000:3000"
      - "39998:39998"
    depends_on:
      - db
    volumes:
      - ".:/todo"
      - "lib_data:/root/.m2/repository"

volumes:
  lib_data:
